---
title: "Data Normalization"
author: "Longping Fu"
date: "03/05/2025"
output: github_document
---

```{r import result, echo = TRUE}
# import packages
library(tidyverse)

# load the peptides result from searching software
peptide_result_raw <- read_csv(
  # the csv file is too large to be uploaded to github
  # change the path to your result files
  'training_data/ronghuwulab_1741203378.csv',
  col_names = TRUE,
  name_repair = 'universal'
)

```

```{r remove contaminants, echo = TRUE}
peptide_result_raw_no_decoy_contaminants <- peptide_result_raw |> 
  # only keep the psm from human proteome
  filter(str_detect(Reference, 'HUMAN')) |> 
  # remove contaminant
  filter(!str_detect(Reference, 'contaminant')) |> 
  # remove decoy
  filter(!str_detect(Reference, '##')) |> 
  # remove low quality PSMs
  # for Sequest, XCorr and PPM are used
  # for other searching software, please use corresponding searching score
  # for example, Hyperscore in MSFragger
  filter(XCorr > 1.2) |> 
  filter(PPM > -10, PPM < 10) |> 
  filter(Sum.Sn > 45) |> 
  separate(Reference, into = c('sp', 'UniProt_Accession', 'protein_name'), sep = '\\|') |> 
  select(
    # keep the columns which are useful in the following data analysis
    Peptide,
    Trimmed.Peptide, 
    Pept.Length = Pept..Length, 
    Start.Position, 
    End.Position, 
    Trypticity, 
    MissedCleav,
    Obs.m.z, 
    XCorr, 
    PPM, 
    UniProt_Accession, 
    Gene.Symbol, 
    Annotation, 
    # rename the TMT channel base on your experimental design
    Iron_1 = ..126.Sn, Iron_2 = ..127n.Sn, Iron_3 = ..127c.Sn,
    Copper_4 = ..128n.Sn, Copper_5 = ..128c.Sn, Copper_6 = ..129n.Sn,
    Ctrl_7 = ..129c.Sn, Ctrl_8 = ..130n.Sn, Ctrl_9 = ..130c.Sn, 
    Sum.Sn
  )
```

```{r protein quantification, echo = TRUE}
# quantification on protein level
protein_quantification <- peptide_result_raw_no_decoy_contaminants |> 
  group_by(
    UniProt_Accession, Gene.Symbol, Annotation
  ) |> 
  summarise(
    Iron_1 = sum(Iron_1),
    Iron_2 = sum(Iron_2),
    Iron_3 = sum(Iron_3),
    Copper_4 = sum(Copper_4),
    Copper_5 = sum(Copper_5),
    Copper_6 = sum(Copper_6),
    Ctrl_7 = sum(Ctrl_7),
    Ctrl_8 = sum(Ctrl_8),
    Ctrl_9 = sum(Ctrl_9)
  ) |> 
  ungroup()
```

```{r check column sum of raw data, echo = TRUE}
# check the sum of each TMT channel
colSums(
  protein_quantification |> select(Iron_1:Ctrl_9)
)
```

```{r sample loading normalization, echo = TRUE}
# sample loading normalization
target_mean_protein <- mean(colSums(protein_quantification |> select(Iron_1:Ctrl_9)))
norm_facs_protein <- target_mean_protein/colSums(protein_quantification |> select(Iron_1:Ctrl_9))
protein_sl <- tibble(
  sweep(
    protein_quantification |> select(Iron_1:Ctrl_9), 
    2, 
    norm_facs_protein, 
    FUN = '*'
  )
)
colnames(protein_sl) <- c(
  'Iron_1_sl', 'Iron_2_sl', 'Iron_3_sl', 
  'Copper_4_sl', 'Copper_5_sl', 'Copper_6_sl',
  'Ctrl_7_sl', 'Ctrl_8_sl', 'Ctrl_9_sl'
)
protein_quantification_raw_sl <- bind_cols(protein_quantification, protein_sl)
```

```{r check column sum of sl normalized data, echo = TRUE}
# check the sum of each TMT channel
colSums(
  protein_quantification_raw_sl |> select(Iron_1_sl:Ctrl_9_sl)
)
```

```{r TMM normalization, echo = TRUE}
# TMM normalization
library(edgeR)

norm_facs_protein_sl_tmm <- calcNormFactors(protein_quantification_raw_sl |> select(Iron_1_sl:Ctrl_9_sl))
protein_tmm <- tibble(
  sweep(
    protein_quantification_raw_sl |> select(Iron_1_sl:Ctrl_9_sl), 
    2, 
    norm_facs_protein_sl_tmm, 
    FUN = "/"
  )
)
colnames(protein_tmm) <- c(
  'Iron_1_sl_tmm', 'Iron_2_sl_tmm', 'Iron_3_sl_tmm', 
  'Copper_4_sl_tmm', 'Copper_5_sl_tmm', 'Copper_6_sl_tmm',
  'Ctrl_7_sl_tmm', 'Ctrl_8_sl_tmm', 'Ctrl_9_sl_tmm'
)
protein_quantification_raw_sl_tmm <- bind_cols(protein_quantification_raw_sl, protein_tmm)
```

```{r check intensity distribution, echo = TRUE}
# check the distribution of the intensity of each channel
protein_quantification_raw_sl_tmm |> 
  select(Iron_1_sl_tmm:Ctrl_9_sl_tmm) |> 
  pivot_longer(cols = Iron_1_sl_tmm:Ctrl_9_sl_tmm, names_to = 'Exp', values_to = 'Intensity') |> 
  mutate(
    log2_intensity = log2(Intensity)
  ) |> 
  ggplot() +
  geom_boxplot(
    aes(
      x = Exp,
      y = log2_intensity
    )
  ) +
  labs(x = '', y = 'log2 intensity') +
  theme(
    axis.text.x = element_text(angle = 30, hjust = 1)
  )
```
