---
title: "Chapter 3: Differential Analysis"
author: "Longping Fu"
date: "03/05/2025"
output: github_document
---

```{r experimental model, echo = TRUE}
# import packages
library(tidyverse)
library(limma)

# experimental model
Experiment_Model <- model.matrix(~ 0 + factor(rep(c("case1", "case2"), each = 3), levels = c("case1", "case2")))
colnames(Experiment_Model) <- c("case1", "case2")
Contrast_Matrix <- makeContrasts(case1_case2 = case1 - case2, levels = Experiment_Model)
```

```{r Iron experiment, echo = TRUE}
# import normalized data
protein_quantification_raw_sl_tmm <- read_csv(
  'training_data/protein_quantification_raw_sl_tmm.csv'
)

# calculate log2 transformed Iron experiment TMT channel intensity
Iron_protein_raw_sl_tmm_log2 <- protein_quantification_raw_sl_tmm |> 
  mutate(
    log2_Iron_1_sl_tmm = log2(Iron_1_sl_tmm),
    log2_Iron_2_sl_tmm = log2(Iron_2_sl_tmm),
    log2_Iron_3_sl_tmm = log2(Iron_3_sl_tmm),
    log2_Ctrl_7_sl_tmm = log2(Ctrl_7_sl_tmm),
    log2_Ctrl_8_sl_tmm = log2(Ctrl_8_sl_tmm),
    log2_Ctrl_9_sl_tmm = log2(Ctrl_9_sl_tmm)
  )

# differential analysis
Iron_protein_raw_sl_tmm_log2_data_matrix <- data.matrix(
  Iron_protein_raw_sl_tmm_log2 |> select(starts_with('log2'))
)
rownames(Iron_protein_raw_sl_tmm_log2_data_matrix) <- Iron_protein_raw_sl_tmm_log2$UniProt_Accession

Iron_protein_lmfit <- lmFit(Iron_protein_raw_sl_tmm_log2_data_matrix, Experiment_Model)
Iron_protein_lmFit_contrast <- contrasts.fit(Iron_protein_lmfit, Contrast_Matrix)
Iron_protein_lmFit_contrast_eBayes <- eBayes(Iron_protein_lmFit_contrast)
Iron_protein_toptable <- topTable(
  Iron_protein_lmFit_contrast_eBayes,
  number = Inf,
  adjust.method = 'BH'
)

rownames_Iron_protein_toptable <- rownames(Iron_protein_toptable)
Iron_protein_toptable_tb <- tibble(Iron_protein_toptable)
Iron_protein_toptable_tb$UniProt_Accession <- rownames_Iron_protein_toptable

write_csv(
  Iron_protein_toptable_tb,
  file = 'training_data/Iron_protein_toptable_tb.csv'
)
```

```{r volcano plot, echo = TRUE}
Iron_protein_toptable_tb |> 
  mutate(
    log10_adjpvalue = -log10(adj.P.Val)
  ) |> 
  ggplot() +
  geom_point(
    aes(
      x = logFC,
      y = log10_adjpvalue
    )
  ) +
  labs(x = 'log2 fold change', y = '-log10 adj.P.value')
```

```{r session info}
sessionInfo()
```