---
title: "Chapter 4: Enrichment Analysis"
author: "Longping Fu"
date: "03/05/2025"
output: github_document
---

```{r GSEA with GO and KEGG for Iron experiment, echo = TRUE}
library(tidyverse)
library(clusterProfiler)
library(org.Hs.eg.db)

# import differential analysis result
Iron_protein_toptable_tb <- read_csv(
  'training_data/Iron_protein_toptable_tb.csv'
)

# generate ranked gene list
# tutorial: https://yulab-smu.top/biomedical-knowledge-mining-book/faq.html
# How to prepare your own geneList
genelist <- Iron_protein_toptable_tb$logFC
names(genelist) <- Iron_protein_toptable_tb$UniProt_Accession
genelist <- sort(genelist, decreasing = TRUE)

# GSEA for GO
Iron_GO_GSEA <- gseGO(
  geneList = genelist,
  # 'ALL' for all 'BP', 'MF', and 'CC'
  ont = 'ALL',
  OrgDb = org.Hs.eg.db,
  # check the manual for org.Hs.eg.db for all available identifiers
  # https://bioconductor.org/packages/release/data/annotation/manuals/org.Hs.eg.db/man/org.Hs.eg.db.pdf
  keyType = 'UNIPROT',
  pvalueCutoff = 1
)

# check GSEA GO result
Iron_GO_GSEA@result |> 
  as_tibble() |> 
  arrange(p.adjust)

# GSEA for KEGG
Iron_KEGG_GSEA <- gseKEGG(
  geneList = genelist,
  # 'hsa' for Homo sapiens (human)
  organism = 'hsa',
  # 'uniprot' for UniProt_Accession
  keyType = 'uniprot',
  pvalueCutoff = 1
)

# check GSEA KEGG result
Iron_KEGG_GSEA@result |> 
  as_tibble() |> 
  arrange(p.adjust)
```

```{r GSEA with CORUM and Pfam for Iron experiment}
## Database Download Instructions
## ==============================
## This section requires two external databases: CORUM and Pfam.
## Follow these steps to download them before running this code:
##
## CORUM Database (Protein Complexes):
## 1. Visit: https://mips.helmholtz-muenchen.de/corum/download
## 2. Download "UniProt-CORUM Mapping" (corum_uniprotCorumMapping.txt)
## 3. Place in the training_data/ folder
##
## Pfam Database (Protein Domains):
## 1. Visit: https://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam37.0/proteomes/
## 2. Download "9606.tsv.gz" (human proteome, ~2.8MB compressed)
## 3. Decompress and place the 9606.tsv file in the training_data/ folder

# CORUM database - protein complex annotations
# Source: https://mips.helmholtz-muenchen.de/corum/download
# UniProt-CORUM Mapping, Corum 5.1 release (2025-01-21)
corum_human <- read_delim(
  'training_data/corum_uniprotCorumMapping.txt',
  col_names = TRUE,
  name_repair = 'universal'
) |>
  mutate(
    corum_id = paste('corum_id', corum_id, sep = '_')
  ) |>
  dplyr::select(corum_id, UniProtKB_accession_number)

# one column for TERM, one column for GENE
# for proteomic result, most of the time GENE refers to UniProt_Accession
colnames(corum_human) <- c('TERM', 'GENE')

# Pfam database - protein domain annotations
# Source: https://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam37.0/proteomes/
# 9606.tsv.gz (human proteome), 2024-05-28
pfam_human <- read_tsv(
  'training_data/9606.tsv',
  skip = 3,
  col_names = FALSE
) |>
  dplyr::select(X6, X1)

# one column for TREM, one column for GENE
colnames(pfam_human) <- c('TERM', 'GENE')

# GSEA for protein complex
Iron_CORUM_GSEA <- GSEA(
  geneList = genelist,
  pvalueCutoff = 1,
  # parameter TERM2GENE, one column for TREM, one column for GENE
  TERM2GENE = corum_human
)

# check GSEA CORUM result
Iron_CORUM_GSEA@result |> 
  as_tibble() |> 
  arrange(p.adjust)

# GSEA for protein domain
Iron_Pfam_GSEA <- GSEA(
  geneList = genelist,
  pvalueCutoff = 1,
  # parameter TERM2GENE, one column for TREM, one column for GENE
  TERM2GENE = pfam_human
)

# check GSEA Pfam result
Iron_Pfam_GSEA@result |> 
  as_tibble() |> 
  arrange(p.adjust)
```

```{r session info}
sessionInfo()
```